# Site
name: "Eixample Respira"
title: "Eixample Respira"
description: "Som una plataforma veÃ¯nal, apartidista, del districte de l'Eixample de Barcelona que compartim una gran preocupaciÃ³ per la qualitat de l'aire que respirem. ðŸš—ðŸ’¨ðŸ˜·"
meta_description: "Som una plataforma veÃ¯nal, apartidista, del districte de l'Eixample de Barcelona que compartim una gran preocupaciÃ³ per la qualitat de l'aire que respirem. ðŸš—ðŸ’¨ðŸ˜·"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/eixample-respira'
email: 'eixample-respira@gmail.com'
google_analytics: 'UA-46278016-1'

# Authors
authors:
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge